# Generated by Django 5.1.1 on 2024-09-21 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='ministries/')),
                ('caption', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('instructions', models.TextField(help_text='Detailed instructions or content about the ministry.')),
                ('tag_for_seo', models.TextField(help_text='Tags for SEO purposes.')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.ministry')),
            ],
        ),
    ]
