# Generated by Django 5.1.1 on 2024-09-22 10:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed instructions or content about the ministry.'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
