# Generated by Django 5.1.1 on 2024-09-21 08:57

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('initiative_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45)),
                ('excert', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('image1', models.ImageField(blank=True, upload_to='initiatives/')),
                ('caption_for_image', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags_for_seo_and_search_bar_in_website', models.TextField(help_text='Add tags for search and SEO purposes.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DriveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image_link', models.URLField()),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_images', to='impact_stories.initiative')),
            ],
        ),
    ]
