# Generated by Django 5.1.1 on 2024-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact_stories', '0002_rename_initiative_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='youtube_video',
            field=models.URLField(blank=True, help_text='Add a YouTube video URL'),
        ),
    ]
