# Generated by Django 5.1.1 on 2024-09-13 05:51

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='author/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('url', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('blog_views', models.IntegerField(default=0, editable=False)),
                ('main_long_title', models.CharField(max_length=250)),
                ('excerpt', models.TextField(max_length=1000)),
                ('thumbnail', models.ImageField(upload_to='post_thumbnail/')),
                ('thumbnail_caption', models.CharField(default='Image related to blog', max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_before_image', ckeditor.fields.RichTextField(blank=True)),
                ('image_for_post', models.ImageField(blank=True, upload_to='image_for_post/')),
                ('caption_for_image', models.CharField(blank=True, max_length=100)),
                ('content_after_image', ckeditor.fields.RichTextField(blank=True)),
                ('quote_related_to_post', models.TextField(blank=True)),
                ('author_of_quote', models.CharField(blank=True, max_length=50)),
                ('tags_for_seo_and_search_bar_in_website', models.TextField(help_text='Add tags(this tags will be for search bar of the webstie as well as for SEO stuffs, so be particular while adding, do research for the keywords, and add properly.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('bookmark', models.ManyToManyField(blank=True, related_name='bookmarked_blogs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
