# Generated by Django 5.1.1 on 2024-10-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
