# Generated by Django 5.1.1 on 2024-09-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('initiative_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(blank=True, max_length=45)),
                ('content', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('google_drive_embed_link', models.CharField(blank=True, max_length=255)),
                ('image1', models.ImageField(upload_to='initiatives/')),
                ('image2', models.ImageField(upload_to='initiatives/')),
                ('caption_for_image', models.CharField(blank=True, max_length=100)),
                ('date_of_initiative', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags_for_seo_and_search_bar_in_website', models.TextField(help_text='Add tags(this tags will be for search bar of the website as well as for SEO stuff.')),
            ],
        ),
    ]
