# Generated by Django 5.1.1 on 2024-09-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_initiative_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='image1',
            field=models.ImageField(blank=True, upload_to='initiatives/'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='image2',
            field=models.ImageField(blank=True, upload_to='initiatives/'),
        ),
    ]
