# Generated by Django 5.1.1 on 2024-09-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_alter_initiative_image1_alter_initiative_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiative',
            old_name='google_drive_embed_link',
            new_name='google_drive_link',
        ),
    ]
