# Generated by Django 5.1.1 on 2024-09-21 06:34

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_rename_google_drive_embed_link_initiative_google_drive_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='google_drive_link',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='image2',
        ),
        migrations.AddField(
            model_name='initiative',
            name='point_wise',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='DriveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image_link', models.URLField()),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_images', to='initiatives.initiative')),
            ],
        ),
    ]
