# Generated by Django 5.1.1 on 2024-09-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_remove_initiative_google_drive_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='excert',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
