# Generated by Django 5.1.1 on 2024-09-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_initiative_excert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='date_of_initiative',
            field=models.DateTimeField(null=True),
        ),
    ]
