# Generated by Django 5.1.1 on 2024-09-21 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0007_alter_initiative_date_of_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='date_of_initiative',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
