# Generated by Django 5.1.1 on 2024-09-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0008_alter_initiative_date_of_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='youtube_video',
            field=models.URLField(blank=True, help_text='Add a YouTube video URL'),
        ),
    ]
